In [17]:
import sys
import numpy as np
from functools import lru_cache

def read_file(file_name):
    data=np.zeros((10,10),np.int64)
    with open(file_name) as input_file:
        lines=input_file.read().splitlines()
        for i in range(0,10):
            line=lines[i]
            for j in range(0,10):
                data[i,j]=int(line[j])
    return data

def increase(board,to_flash):
    for i in range(0,10):
        for j in range(0,10):
            board[i,j] +=1;
            if board[i,j]>9:
                to_flash.append([i,j])

def flash(board,to_flash,flashed):
    i0,j0=to_flash.pop()
    if flashed[i0,j0]==0:
        flashed[i0,j0]=1
        imin=max(0,i0-1)
        imax=min(9,i0+1)
        jmin=max(0,j0-1)
        jmax=min(9,j0+1)
        for i in range(imin,imax+1):
            for j in range(jmin,jmax+1):
                board[i,j] += 1
                if board[i,j]>9:
                    to_flash.append([i,j])  
        return 1;
    else:
        return 0;
    
def reset(board,flashed):
    for i in range(0,10):
        for j in range(0,10):
            if flashed[i,j]==1:
                flashed[i,j]=0;
                board[i,j]=0;
                
if __name__ == '__main__':
    #read lines
    board=read_file('input')
    
    to_flash=[]
    flashed=board*0
    count=0
    print(board)
    for i in range(0,100):
        increase(board,to_flash)
        while len(to_flash)>0:
            count += flash(board,to_flash,flashed)
        reset(board,flashed)

    print(board)
    print(count)

[[1 4 4 3 5 8 2 1 4 8]
 [6 5 5 3 7 3 4 8 5 1]
 [1 4 5 1 7 4 1 2 4 6]
 [8 8 3 5 2 1 8 8 6 4]
 [1 6 6 2 3 1 7 2 6 2]
 [1 7 3 1 6 5 6 6 2 3]
 [1 1 2 8 1 7 8 3 6 7]
 [5 8 4 2 3 5 1 6 6 5]
 [6 6 7 7 3 2 6 8 4 3]
 [7 3 8 1 4 3 3 2 6 7]]
[[3 7 8 1 2 0 0 0 0 0]
 [6 8 1 1 2 3 4 4 5 0]
 [5 8 1 1 1 1 1 1 2 2]
 [5 7 1 1 1 1 1 1 1 1]
 [5 6 9 1 1 1 6 6 1 1]
 [5 6 9 4 5 4 3 3 5 1]
 [6 8 2 2 2 2 2 2 3 3]
 [8 3 2 2 2 2 2 2 3 3]
 [1 5 3 2 2 3 4 5 6 0]
 [1 1 3 2 2 3 1 2 0 0]]
1717


In [7]:
import sys
import numpy as np
from functools import lru_cache

def read_file(file_name):
    data=np.zeros((10,10),np.int64)
    with open(file_name) as input_file:
        lines=input_file.read().splitlines()
        for i in range(0,10):
            line=lines[i]
            for j in range(0,10):
                data[i,j]=int(line[j])
    return data

def increase(board,to_flash):
    for i in range(0,10):
        for j in range(0,10):
            board[i,j] +=1;
            if board[i,j]>9:
                to_flash.append([i,j])

def flash(board,to_flash,flashed):
    i0,j0=to_flash.pop()
    if flashed[i0,j0]==0:
        flashed[i0,j0]=1
        imin=max(0,i0-1)
        imax=min(9,i0+1)
        jmin=max(0,j0-1)
        jmax=min(9,j0+1)
        for i in range(imin,imax+1):
            for j in range(jmin,jmax+1):
                board[i,j] += 1
                if board[i,j]>9:
                    to_flash.append([i,j])  
        return 1;
    else:
        return 0;
    
def reset(board,flashed):
    for i in range(0,10):
        for j in range(0,10):
            if flashed[i,j]==1:
                flashed[i,j]=0;
                board[i,j]=0;
                
if __name__ == '__main__':
    #read lines
    board=read_file('input')
    
    to_flash=[]
    flashed=board*0
    
    for i in range(0,2000):
        count=0
        increase(board,to_flash)
        while len(to_flash)>0:
            count += flash(board,to_flash,flashed)
        reset(board,flashed)
        if count==100:
            print("first collective flash at time {}" .format(i+1))
            print(board)
            count=0
            sys.exit()
        else:
            count=0
        


[[1 4 4 3 5 8 2 1 4 8]
 [6 5 5 3 7 3 4 8 5 1]
 [1 4 5 1 7 4 1 2 4 6]
 [8 8 3 5 2 1 8 8 6 4]
 [1 6 6 2 3 1 7 2 6 2]
 [1 7 3 1 6 5 6 6 2 3]
 [1 1 2 8 1 7 8 3 6 7]
 [5 8 4 2 3 5 1 6 6 5]
 [6 6 7 7 3 2 6 8 4 3]
 [7 3 8 1 4 3 3 2 6 7]]
first collective flash at time 475
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


SystemExit: 